2024-04-22 20:14:35,783 - __main__ - INFO - Starting paper ranking process...
2024-04-22 20:14:35,784 - __main__ - INFO - Paper ranking process completed.
2024-04-22 20:15:18,010 - __main__ - INFO - Starting paper ranking process...
2024-04-22 20:15:18,010 - __main__ - INFO - Paper ranking process completed.
2024-04-22 20:15:47,635 - __main__ - INFO - Starting paper ranking process...
2024-04-22 20:15:47,635 - __main__ - INFO - Paper ranking process completed.
2024-04-22 20:15:54,397 - __main__ - INFO - Starting paper ranking process...
2024-04-22 20:15:54,397 - __main__ - INFO - Paper ranking process completed.
2024-04-22 20:17:20,952 - __main__ - INFO - Starting paper ranking process...
2024-04-22 20:17:20,952 - __main__ - INFO - Paper ranking process completed.
2024-04-22 20:18:37,652 - __main__ - INFO - Starting paper ranking process...
2024-04-22 20:20:11,475 - __main__ - WARNING - Received None response from the Gemini API. Skipping query.
2024-04-22 20:20:21,708 - __main__ - INFO - Paper ranking process completed.
2024-04-23 08:04:59,030 - __main__ - INFO - Starting paper ranking process...
2024-04-23 08:05:08,897 - __main__ - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 08:06:22,568 - __main__ - INFO - Starting paper ranking process...
2024-04-23 08:06:27,925 - __main__ - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 08:07:56,941 - __main__ - WARNING - Received None response from the Gemini API. Skipping query.
2024-04-23 08:08:09,238 - __main__ - INFO - Paper ranking process completed.
2024-04-23 08:15:59,108 - __main__ - INFO - Starting paper ranking process...
2024-04-23 08:17:33,875 - __main__ - WARNING - Received None response from the Gemini API. Skipping query.
2024-04-23 08:17:39,002 - __main__ - INFO - Paper ranking process completed.
2024-04-23 08:39:28,879 - __main__ - INFO - Starting paper ranking process...
2024-04-23 08:40:28,810 - __main__ - INFO - Paper ranking process completed.
2024-04-23 09:21:08,159 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:21:12,062 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:21:16,643 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:21:20,743 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:21:20,743 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-23 09:29:55,524 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:30:01,707 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:30:04,487 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:30:14,768 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:30:44,760 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:30:49,886 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:30:51,270 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:30:55,657 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:31:00,776 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:31:06,425 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:31:07,953 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:31:09,543 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:31:17,884 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:31:25,976 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:31:44,570 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:31:49,298 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:31:54,619 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:31:59,702 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:32:01,805 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:32:05,744 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:32:09,676 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:32:13,604 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:32:13,926 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:32:27,292 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:32:39,586 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:32:43,480 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:32:44,596 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:32:44,608 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-23 09:32:49,514 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:32:52,951 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:32:58,575 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:32:58,575 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-23 09:33:00,623 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:33:06,780 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:33:06,781 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-23 09:33:12,992 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:33:15,811 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 09:33:15,813 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-23 09:34:26,733 - __main__ - INFO - Starting paper ranking process...
2024-04-23 09:35:30,854 - __main__ - INFO - Paper ranking process completed.
2024-04-23 09:44:20,326 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 09:46:00,933 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 09:46:21,215 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 09:46:25,416 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 09:46:25,416 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-23 09:46:25,416 - analyze_papers - WARNING - Invalid relevance score for query query_8. Skipping paper.
2024-04-23 11:11:36,118 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 11:11:44,499 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 11:13:06,803 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 11:13:14,892 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 11:13:33,332 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 11:13:44,780 - analyze_papers - WARNING - Invalid relevance score for query query_2. Skipping paper.
2024-04-23 11:13:44,790 - analyze_papers - WARNING - Invalid relevance score for query query_6. Skipping paper.
2024-04-23 11:13:44,790 - analyze_papers - WARNING - Invalid relevance score for query query_7. Skipping paper.
2024-04-23 11:13:44,790 - analyze_papers - WARNING - Invalid relevance score for query query_10. Skipping paper.
2024-04-23 14:31:15,201 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 14:31:18,681 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 14:31:42,395 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 14:32:07,547 - analyze_papers - WARNING - Received None response from the Gemini API. Skipping query.
2024-04-23 14:32:09,484 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 14:32:21,460 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 14:32:32,031 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 14:32:40,254 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 14:32:43,170 - analyze_papers - WARNING - Received None response from the Gemini API. Skipping query.
2024-04-23 14:32:46,290 - analyze_papers - WARNING - Received None response from the Gemini API. Skipping query.
2024-04-23 14:33:05,805 - analyze_papers - WARNING - Received None response from the Gemini API. Skipping query.
2024-04-23 14:33:09,074 - analyze_papers - WARNING - Received None response from the Gemini API. Skipping query.
2024-04-23 15:36:44,763 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 15:37:51,800 - analyze_papers - WARNING - Invalid relevance score for query query_4. Skipping paper.
2024-04-23 16:04:07,159 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 16:04:59,026 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-23 18:51:57,001 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 18:52:00,018 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 18:52:02,960 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 18:52:06,439 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 18:52:06,439 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-23 18:54:14,156 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 18:54:17,179 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 18:54:20,175 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 18:54:23,187 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-23 18:54:23,199 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-24 08:27:44,322 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 08:27:48,195 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 08:27:52,213 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 08:27:56,151 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 45, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 08:27:56,161 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-24 08:40:58,923 - __main__ - INFO - Starting paper ranking process...
2024-04-24 08:42:27,231 - __main__ - INFO - Paper ranking process completed.
2024-04-24 08:50:30,667 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-24 08:50:48,709 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-24 08:51:06,571 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-24 08:51:23,192 - analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-24 08:51:23,203 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-24 09:37:31,428 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 09:37:35,804 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 09:37:40,166 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 09:37:44,610 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 09:37:44,620 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-24 10:01:30,727 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 10:01:35,518 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 10:01:40,414 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 10:01:45,168 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 10:01:45,170 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-24 10:03:00,417 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 10:03:04,852 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 10:03:09,314 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 10:03:13,921 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 10:03:13,921 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-24 10:03:18,462 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 10:03:22,900 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 10:03:27,228 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 10:03:31,701 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-24 10:03:31,702 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 07:22:12,176 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:22:18,981 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:22:27,125 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:22:33,273 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:22:33,281 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 07:22:39,036 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:22:44,753 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:22:50,268 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:22:58,886 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:22:58,891 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 07:23:05,321 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:23:12,826 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:23:20,681 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:23:28,191 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:23:28,198 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 07:23:35,503 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:23:42,246 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:23:48,930 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:23:54,551 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:23:54,551 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 07:24:02,031 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:24:09,818 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:36:38,309 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:36:44,855 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:36:49,670 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:36:56,227 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:36:56,233 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 07:38:59,041 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:39:03,610 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:39:10,779 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:39:17,129 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 07:39:17,139 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 17:14:07,139 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:14:10,811 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:14:14,629 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:14:18,560 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:14:18,562 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 17:14:22,049 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:14:25,752 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:14:29,571 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:14:33,345 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:14:33,345 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 17:15:00,115 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:15:04,133 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:15:08,076 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:15:11,895 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:15:11,898 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 17:15:36,574 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:15:40,410 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:15:44,242 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:15:48,042 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 17:15:48,045 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 18:45:39,107 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:45:42,479 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:45:46,316 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:45:49,719 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:45:49,729 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 18:46:38,168 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:46:41,922 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:46:45,944 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:46:49,748 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:46:49,748 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 18:50:28,783 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:50:32,605 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:50:36,507 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:50:39,970 - analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:50:39,973 - analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 18:58:26,726 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:58:30,429 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:58:34,238 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:58:38,275 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 18:58:38,284 - utils.analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 19:00:13,595 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 19:00:16,986 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 19:00:57,620 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 19:01:01,713 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 19:01:05,274 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 19:01:09,108 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 19:01:09,114 - utils.analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-25 19:10:57,750 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 19:11:01,433 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 19:11:05,243 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 19:11:09,007 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-25 19:11:09,015 - utils.analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-29 13:48:48,541 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:48:53,242 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:48:58,125 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:49:03,833 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:49:03,841 - utils.analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-29 13:54:09,129 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:54:13,989 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:54:18,694 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:54:24,286 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:54:24,286 - utils.analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-29 13:54:29,085 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:54:34,470 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:54:39,602 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:54:44,857 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:54:44,857 - utils.analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-29 13:55:36,264 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:55:41,060 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:55:46,533 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:55:51,771 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:55:51,783 - utils.analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-29 13:57:11,429 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:57:16,240 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:57:21,728 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:57:26,531 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:57:26,532 - utils.analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-29 13:57:40,167 - utils.analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-29 13:57:54,751 - utils.analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-29 13:58:09,472 - utils.analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-29 13:59:00,381 - utils.analyze_papers - WARNING - Invalid JSON response for the current query. Retrying immediately...
2024-04-29 13:59:53,492 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 13:59:59,217 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 14:00:04,142 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 14:00:08,948 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 14:00:08,951 - utils.analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-29 16:16:01,999 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:16:07,069 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:16:13,630 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:16:19,373 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:16:19,381 - utils.analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-29 16:16:24,633 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:16:30,043 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:16:35,194 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:16:41,632 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:16:41,633 - utils.analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-29 16:16:46,813 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:16:52,015 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:16:57,208 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:17:03,295 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:17:03,295 - utils.analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-29 16:17:33,625 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:17:40,221 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:17:45,901 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:17:52,346 - utils.analyze_papers - ERROR - Error processing query: 'DOI'
Traceback (most recent call last):
  File "c:\Users\bnsoh2\OneDrive - University of Nebraska-Lincoln\Documents\Coding Projects\Automated_Lit_Revs - Demo\utils\analyze_papers.py", line 46, in process_query
    json_data["DOI"] = query_data["DOI"]
                       ~~~~~~~~~~^^^^^^^
KeyError: 'DOI'
2024-04-29 16:17:52,356 - utils.analyze_papers - ERROR - Max retries reached for current query. Skipping query.
2024-04-29 16:43:01,925 - utils.analyze_papers - WARNING - Discarding query query_3 due to missing DOI or title.
2024-04-29 16:43:01,925 - utils.analyze_papers - WARNING - Discarding query query_8 due to missing DOI or title.
2024-04-29 17:56:34,307 - utils.analyze_papers - WARNING - Discarding query query_1 due to missing DOI or title.
2024-04-29 17:56:34,307 - utils.analyze_papers - WARNING - Discarding query query_4 due to missing DOI or title.
2024-04-29 17:56:34,307 - utils.analyze_papers - WARNING - Discarding query query_10 due to missing DOI or title.
